### ISSUE TITLE
Allow me to ignore CRLF differences as an option

### ISSUE THREAD

**Issue by ptyagi16** [samg/diffy#105]
When I have differences in only the CRLF where text A is from windows and text B is from unix then I should be able to ignore differences only in CRLF characters

**Comment by ptyagi16** [comment]
Thanks @samg !!  When is the next release?

**Comment by samg** [comment]
I will try to push a new version later this week.  Thanks!

**Comment by ptyagi16** [comment]
Cool.  Thanks man
