### ISSUE TITLE
Security Policy

### ISSUE THREAD

**Issue by tehryanx** [samg/diffy#117]
Hey Sam!
I'd like to report a security issue but this project doesn't have a security policy. What's a safe way to get the details to you? 
Thanks!

**Comment by ErCargo** [comment]
您好，邮件已收到！

**Comment by samg** [comment]
Security fix was released in version [3.4.1])(https://rubygems.org/gems/diffy/versions/3.4.1).  Thanks for reporting @tehryanx!
