### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by tadast** [samg/diffy#66]
Hello Sam,

great gem, thanks for writing it. Looks like the current master has some useful things in it that have not been released as a gem yet. Would it be possible to release a new version?

**Comment by hawthorneluke** [comment]
I'd very much like this too please.

**Comment by samg** [comment]
Your wish is my command :joy_cat: 
https://rubygems.org/gems/diffy/versions/3.1.0

Enjoy!

**Comment by hawthorneluke** [comment]
Thank you!
