### ISSUE TITLE
Linux diff not found

### ISSUE THREAD

**Issue by MisterTakaashi** [samg/diffy#71]
Hello, I dev on my Windows but my production server is an Ubuntu 14.04. When I deployed my application in production, Diffy gem was installed, but when I use it, it said:

RuntimeError (Can't find a diff executable in PATH /usr/local/lib/ruby/gems/2.3.0/bin):

Here is a screen of my linux diff package:
[http://prntscr.com/b6105m](http://prntscr.com/b6105m)

Thanks for help :+1:

**Comment by MisterTakaashi** [comment]
Ok, finally I found the solution, I watched the code, and I set the Environnement variable "DIFFY_DIFF", I set: `'/usr/bin/diff'` which is my diff path.

Sorry about that and thank :heart:

**Comment by ballPointPenguin** [comment]
I'm having the same problem in my linux docker container. I will try the DIFFY_DIFF=/usr/bin/diff solution, but I do wonder why Diffy is failing to identify my diff binary in the first place.
