### ISSUE TITLE
Bug: Lines with dashes are dropped when different

### ISSUE THREAD

**Issue by ninewise** [samg/diffy#77]
When a line on the left side of a diff starts with `--`, the line is dropped from the diff. When running `puts Diffy::Diff.new("aa\n--\ncc\n", "aa\nbb\ncc\n")` you get:
```
 aa
+bb
 cc
```

but you'd expect:
```
 aa
---
+bb
 cc
```

More examples:
```ruby
puts Diffy::Diff.new("a a\n-- b\nc c", "a a\nb b\nc c") # fails
puts Diffy::Diff.new("a a\n- b\nc c", "a a\nb b\nc c") # works
puts Diffy::Diff.new("a\n-\nc", "a\nb\nc") # works
puts Diffy::Diff.new("a\n---\nc", "a\n----\nc") # fails
```

Diffy's been serving us really well otherwise, btw, so thanks for the great work!

**Comment by samg** [comment]
Looks like the issue is the regex at https://github.com/samg/diffy/blob/master/lib/diffy/diff.rb#L85.  I'll see if I can get a fix in in the next few days.

**Comment by bmesuere** [comment]
Any progress on a fix?
