### ISSUE TITLE
:include-diff-info => false may cause some non-diff-info lines to be omitted

### ISSUE THREAD

**Issue by ouroboros8** [samg/diffy#92]
By default diffy omits diff info lines by matching against the regex `/^(---|\+\+\+|@@|\\\\)/`. Unfortunately this means that if a line starting with `--` is removed, or a line starting with `++` is added, diffy will assume that the line is diff info and omit it.

**Comment by samg** [comment]
Thanks.  This is a known issue with diffy.  https://github.com/samg/diffy/issues/77 . 

I don't currently have the bandwidth to fix it, but if someone is willing to propose and PR a fix I'd be happy to review and release it.
